---
title: "Khudji tooth decontamination"
author: "Zandra Fagernäs"
date: "11.06.2024"
---

This R Notebook contains code for the Khudji tooth decontamination portion of "Cleaning the Dead: Optimized decontamination enhances palaeoproteomic analyses of a Pleistocene hominin tooth from Khudji, Tajikistan" by Fagernäs et al.

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(MetBrewer)
library(readr)
library(janitor)
library(ggpubr)
library(Hmisc)
library(ape)
library(Peptides)
library(tidyverse)
```

## Protein count

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width=4, fig.height=4}
# Load text file with protein groups and clean 
original <- read_delim("<PATH_TO>/proteinGroups.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
  filter(!str_detect(protein_names, "Trypsin")) %>%
  filter(!str_detect(protein_i_ds, "CON__P00761")) %>%
  dplyr::select(protein_i_ds, protein_names, razor_unique_peptides_p0441_77min) %>%
  filter(razor_unique_peptides_p0441_77min > 1)
  
bleach <- read_delim("<PATH_TO>/proteinGroups.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+"))  %>%
  filter(!str_detect(protein_names, "Trypsin")) %>%
  filter(!str_detect(protein_i_ds, "CON__P00761")) %>%
  dplyr::select(protein_i_ds, protein_names, razor_unique_peptides_blank) %>%
  filter(razor_unique_peptides_blank > 1)

# Combine files
protein <- full_join(original, bleach)

# Assign origin of protein
protein <- protein %>%
  mutate(skin = str_detect(protein_names, 
       "Keratin|Serum|Filaggrin|Hornerin|Cystatin-A|Dermcidin|Desmoglein-1|Calmodulin|Serpin|Caspase|Suprabasin")) %>%
  mutate(bone = str_detect(protein_names, "Collagen|EMI")) %>%
  mutate(other = str_detect(protein_names, "Alpha-amylase|Ig |Ubiquitin|Lysozyme| C1q|Scavenger")) %>%
  mutate(tissue = if_else(skin == TRUE, "skin", 
                          if_else(bone == TRUE, "bone", "other"))) %>%
  select(-skin, -bone, -other)

# Long form
protein <- protein %>%
  pivot_longer(names_to = "sample", values_to = "peptides", 3:4) %>%
  filter(peptides > 0)

# Clean up sample names
protein <- protein %>%
    mutate(sample = gsub('razor_unique_peptides_p0441_77min', 'Original', sample)) %>%
    mutate(sample = gsub('razor_unique_peptides_blank', 'Bleach', sample))

# Count proteins 
protein_summary <- protein %>%
  group_by(sample, tissue) %>%
  summarize(proteins = sum(peptides > 0),
            peptides = sum(peptides))

# Long format
protein_summary <- protein_summary %>%
  pivot_longer(names_to = "measure", values_to = "count", 3:4)

# Plot 
summary_fig <- ggplot(protein_summary, aes(x=sample, y=count, fill=tissue)) +
  geom_bar(position="fill", stat = "identity") +
  facet_wrap(~measure, scales = "free_y") +
  scale_fill_manual(values=met.brewer("Cassatt2", 3)) +
  theme_bw()
```

## PSM count

```{r}
# Load dataset
original <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
  filter(!str_detect(protein_names, "Trypsin")) %>%
  filter(!str_detect(proteins, "CON__P00761")) %>%
  filter(experiment == "P0441_77min") %>%
  filter(intensity > 0) %>%
  select(proteins, protein_names, experiment, intensity)
  
bleach <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+"))  %>%
  filter(!str_detect(protein_names, "Trypsin")) %>%
  filter(!str_detect(proteins, "CON__P00761")) %>%
  filter(experiment == "Blank") %>%
  filter(intensity > 0) %>%
  select(proteins, protein_names, experiment, intensity)

# Combine files
psm <- full_join(original, bleach)

# Assign origin of protein
psm <- psm %>%
  mutate(skin = str_detect(protein_names, 
       "Keratin|Serum|Filaggrin|Hornerin|Cystatin-A|Dermcidin|Desmoglein-1|Calmodulin|Serpin|Caspase|Suprabasin")) %>%
  mutate(bone = str_detect(protein_names, "Collagen|EMI")) %>%
  mutate(other = str_detect(protein_names, "Alpha-amylase|Ig |Ubiquitin|Lysozyme| C1q|Scavenger")) %>%
  mutate(tissue = if_else(skin == TRUE, "skin", 
                          if_else(bone == TRUE, "bone", "other"))) %>%
  select(-skin, -bone, -other)

# PSM count
psm_count <- psm %>%
  group_by(experiment, tissue) %>%
  dplyr::summarize(psm_count = n())
```

## Peptide length 

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Load data
original <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
  filter(!experiment == "P0442_77min_Blank") %>%
  dplyr::select(length, experiment, intensity) %>%
  mutate(experiment = gsub('P0441_77min', 'Original', experiment))
original_bone <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
  filter(!str_detect(protein_names, "Trypsin|Keratin|Serum|Filaggrin|Hornerin|Cystatin-A|Dermcidin|Desmoglein-1|Calmodulin|Serpin|Caspase|Suprabasin|Alpha-amylase|Ig |Ubiquitin|Lysozyme| C1q|Scavenger|salivary|Zinc|Prolactin|Junction|Gliomedin|Desmo|Cystein|Polyadenylate")) %>%
  filter(!is.na(protein_names)) %>%
  filter(!experiment == "P0442_77min_Blank") %>%
  dplyr::select(length, experiment, intensity) %>%
  mutate(experiment = gsub('P0441_77min', 'Original_bone', experiment))
bleach <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
  filter(experiment == "Blank") %>%
  dplyr::select(length, experiment, intensity) %>%
  mutate(experiment = gsub('Blank', 'Bleach', experiment))
bleach_bone <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
filter(!str_detect(protein_names, "Trypsin|Keratin|Serum|Filaggrin|Hornerin|Cystatin-A|Dermcidin|Desmoglein-1|Calmodulin|Serpin|Caspase|Suprabasin|Alpha-amylase|Ig |Ubiquitin|Lysozyme| C1q|Scavenger|salivary|Zinc|Prolactin|Junction|Gliomedin|Desmo|Cystein|Collectin|Leucine|Baculoviral")) %>%
  filter(experiment == "Blank") %>%
  dplyr::select(length, experiment, intensity) %>%
  mutate(experiment = gsub('Blank', 'Bleach_bone', experiment))

# Combine all
length <- full_join(original, 
                      full_join(original_bone, 
                                full_join(bleach, bleach_bone))) %>%
  filter( intensity > 0)

# Sum intensity by length
length_summary <- length %>%
  group_by(experiment, length) %>%
  dplyr::summarize(total_intensity = sum(intensity))

# Plot barcharts
length_plot <- ggplot(length, aes(x=length, y=total_intensity, fill=experiment)) + 
  geom_bar(stat="identity") +
  facet_wrap(~experiment, ncol=1) +
  scale_fill_manual(values=met.brewer("Cassatt2", 4), name="Proteome") +
  xlab("Peptide length") +
  ylab("Total intensity") +
  theme_bw() +  
  theme(strip.background = element_blank(), strip.text = element_blank())

# Extract comparisons
full <- length %>%
  filter(experiment %in% c("Original", "Bleach"))
bone <- length %>%
  filter(experiment %in% c("Original_bone", "Bleach_bone"))

# Find Box-Cox transformation of the data
MASS::boxcox(lm(length ~ experiment, data=bone))

# Checking transformation
ggqqplot(bone$length)
hist(bone$length)

# Additive model 
model1 <- lm(length ~ experiment, weights=intensity, data = bone)

# Null model
model0 <- lm(length ~ 1, weights=intensity, data = bone)

# Compare models
anova(model1, model0) 

# Check model
plot(model1)
qqnorm(resid(model1))
qqline(resid(model1)) 
```

## Deamidation

```{r}
# Load data
deamidation <- read.csv("<PATH_TO>/deamidation_khudji_manuscript.txt", sep="") %>%
  clean_names()

# Edit sample names
deamidation <- deamidation %>%
   mutate(raw_file = gsub('20230614_EXPL8_nLC11_GT_collab_77min_DDA_P0441', 'original', raw_file)) %>%
   mutate(raw_file = gsub('20231005_EXPL5_nLC11_GT_collab_77min_DDA_Blank_P0581', 'bleach', raw_file))

# Fix version column
deamidation <- deamidation %>%
   mutate(version = gsub('original_bone', 'bone', version)) %>%
   mutate(version = gsub('bleach_bone', 'bone', version)) %>%
   mutate(version = gsub('bleach', 'full', version)) %>%
   mutate(version = gsub('original', 'full', version))

# Plot
deamidation_fig <- ggplot(deamidation, aes(x=raw_file, y=mean, fill=version)) + 
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin=mean-std, ymax=mean+std), width=.2,
                 position=position_dodge(.9)) +
  scale_fill_manual(values=met.brewer("Cassatt2", 2), name="Proteome") +
  facet_grid(~n_q) +
  xlab("") + 
  ylab("Deamidation") +
  theme_bw() 
```

## Hydrophobicity

```{r}
# Load data
original <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
  filter(!experiment == "P0442_77min_Blank") %>%
  dplyr::select(sequence, experiment, intensity) %>%
  mutate(experiment = gsub('P0441_77min', 'Original', experiment))
original_bone <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
  filter(!str_detect(protein_names, "Trypsin|Keratin|Serum|Filaggrin|Hornerin|Cystatin-A|Dermcidin|Desmoglein-1|Calmodulin|Serpin|Caspase|Suprabasin|Alpha-amylase|Ig |Ubiquitin|Lysozyme| C1q|Scavenger|salivary|Zinc|Prolactin|Junction|Gliomedin|Desmo|Cystein|Polyadenylate")) %>%
  filter(!is.na(protein_names)) %>%
  filter(!experiment == "P0442_77min_Blank") %>%
  dplyr::select(sequence, experiment, intensity) %>%
  mutate(experiment = gsub('P0441_77min', 'Original_bone', experiment))
bleach <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
  filter(experiment == "Blank") %>%
  dplyr::select(sequence, experiment, intensity) %>%
  mutate(experiment = gsub('Blank', 'Bleach', experiment))
bleach_bone <- read_delim("<PATH_TO>/evidence.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) %>%
  clean_names() %>%
  filter(!reverse %in% c("+")) %>%
filter(!str_detect(protein_names, "Trypsin|Keratin|Serum|Filaggrin|Hornerin|Cystatin-A|Dermcidin|Desmoglein-1|Calmodulin|Serpin|Caspase|Suprabasin|Alpha-amylase|Ig |Ubiquitin|Lysozyme| C1q|Scavenger|salivary|Zinc|Prolactin|Junction|Gliomedin|Desmo|Cystein|Collectin|Leucine|Baculoviral")) %>%
  filter(experiment == "Blank") %>%
  dplyr::select(sequence, experiment, intensity) %>%
  mutate(experiment = gsub('Blank', 'Bleach_bone', experiment))

# Combine files
evidence <- full_join(original, 
                      full_join(original_bone, 
                                full_join(bleach, bleach_bone))) %>%
  filter( intensity > 0)

# Calculate hydrophobicity
evidence <- evidence %>% 
  filter(intensity > 0) %>%
  mutate(hydro = hydrophobicity(sequence, scale = "KyteDoolittle"))

# Summarize
hydro_summary <- evidence %>%
  group_by(experiment) %>%
  dplyr::summarise(mean_hydro = weighted.mean(x=hydro, w=intensity, na.rm=TRUE),
                   weighted_var= wtd.var(x=hydro, w=intensity, na.rm=TRUE))
hydro_summary$weighted_sd <- sqrt(hydro_summary$weighted_var)

# Edit labels
hydro_summary <- hydro_summary %>%
  separate(experiment, c("experiment", "proteome"), sep="_") %>%
  mutate(proteome = replace_na(proteome, "full"))

# Plot
hydro_fig <- ggplot(hydro_summary, aes(x=experiment, y=mean_hydro, colour=proteome)) + 
  geom_point(position=position_dodge(.9), size=5) +
  geom_errorbar(aes(ymin=mean_hydro-weighted_sd, ymax=mean_hydro+weighted_sd), width=.2,
                 position=position_dodge(.9)) +
  scale_colour_manual(values=met.brewer("Cassatt2", 2), name="Proteome") +
  xlab("") +
  ylab("Hydrophobicity") +
  theme_bw()

# Extract comparisons
full <- evidence %>%
  filter(experiment %in% c("Original", "Bleach"))
bone <- evidence %>%
  filter(experiment %in% c("Original_bone", "Bleach_bone"))

# Find Box-Cox transformation of the data
MASS::boxcox(lm(hydro+3 ~ experiment, data=bone))

# Checking transformation
ggqqplot(bone$hydro)
hist(bone$hydro)

# Additive model 
model1 <- lm(hydro ~ experiment, weights=intensity, data = bone)

# Null model
model0 <- lm(hydro ~ 1, weights=intensity, data = bone)

# Compare models
anova(model1, model0) 

# Check model
plot(model1)
qqnorm(resid(model1))
qqline(resid(model1)) 
```
